version:             "2"
services:
  web:
    ports:
      - "8080:8080"
      - "8443:8443"
  php:
    build:
      args:
        XDEBUG_HOST: ${XDEBUG_HOST}
        XDEBUG_CONF: conf.d
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./docker/php/resources/config/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  postgres:
    ports:
      - "5432:5432"
  adminer:
    container_name:  adminer
    image:           adminer
    restart:         always
    environment:
      ADMINER_DESIGN: "pepa-linha"
      ADMINER_PLUGINS: "enum-types enum-option edit-calendar tables-filter dump-json"
    ports:
      - 8765:8080
    networks:
      - webapp-network
  mailhog:
    container_name:  mailhog
    image:           mailhog/mailhog
    restart:         always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - webapp-network
  browser:
    container_name: browser
    build: ./docker/browser
    restart: always
    ports:
      - 4444:4444
    networks:
      - webapp-network
