version: "2"

services:
  web:
    container_name: web
    build:
        context: ./docker/nginx
        args:
          BUILD_ENV: PRODUCTION
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/resources/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/var/www/html
    networks:
      - webapp-network
  php:
    container_name: php
    build: ./docker/php
    restart: always
    volumes:
      - ./webapp:/var/www/html
    networks:
      - webapp-network
  postgres:
    container_name: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@$$W0rd}
      POSTGRES_DB: webapp
    build: ./docker/postgres
    restart: always
    volumes:
      - ./storage/postgresql:/var/lib/postgresql/data
    networks:
      - webapp-network

networks:
    webapp-network:
        driver: bridge
