version: "2"

services:
  web:
    container_name: web
    image:   nginx:1.13
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/var/www/webapp
    networks:
      - webapp-network
  php:
    container_name: php
    build:
        context: ./docker/php
        args:
          - BUILD_ENV=PRODUCTION
    environment:
      - BUILD_ENV=PRODUCTION
    restart: always
    volumes:
      - ./webapp:/var/www/webapp
    networks:
      - webapp-network
  postgres:
    container_name: postgres
    image:   postgres:10.1
    restart: always
    volumes:
      - ./storage/postgresql:/var/lib/postgresql
    networks:
      - webapp-network

networks:
    webapp-network:
        driver: bridge
