version: "2"

services:
  web:
    ports:
      - "8080:80"
      - "8443:443"
  php:
    build:
      args:
        BUILD_ENV: DEVELOPMENT
    volumes:
      - ./docker/php/resources/config/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  postgres:
    ports:
      - "5432:5432"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8765:8080
    networks:
      - webapp-network
